wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1662992235.690421
    t:
      1:
      - 1
      - 12
      - 45
      - 55
      2:
      - 1
      - 12
      - 45
      - 55
      3:
      - 2
      - 23
      4: 3.8.10
      5: 0.13.2
      8:
      - 1
      - 5
